// Shared display labels for the continent/mode-tag taxonomy in AgencySummary
// (see dashboard/api/agency_metadata.yaml, generated by
// scripts/gen_agency_metadata.py). Defined once so the homepage drill-down
// and the agency browser groupings can't drift out of sync with each other.
//
// An agency's classification is a tag *set*, not a single bucket: an agency
// running buses, ferries and commuter rail carries all three tags and is
// listed under all three sections.

import type { AgencySummary } from "./types";

export const AGENCY_TYPE_LABELS: Record<string, string> = {
  subway_metro: "Subway/Metro",
  light_rail_streetcar: "Light Rail/Streetcar",
  commuter_rail: "Commuter Rail",
  bus_rta: "Bus",
  ferry_other: "Ferry+Other",
};

export const AGENCY_TYPE_ORDER = Object.keys(AGENCY_TYPE_LABELS);

export const UNCLASSIFIED_LABEL = "Unclassified";

// continent codes are feed-cluster boxes (see archiver/region.py), not
// literal continents -- e.g. "eu" also covers Africa and most of the Middle
// East, "au" covers most of Asia-Pacific. Label them accordingly rather than
// rendering the raw box code as if it were geographically precise.
export const CONTINENT_LABELS: Record<string, string> = {
  us: "Americas",
  eu: "Europe / Africa / Middle East",
  au: "Asia-Pacific",
};

/**
 * An agency's mode tags. Falls back to the deprecated scalar `type` so a
 * dashboard build pointed at an API from before the tag migration still
 * classifies agencies (as a single tag) rather than dumping every one of
 * them into Unclassified. Empty means unclassified.
 */
export function agencyTypeTags(agency: AgencySummary): string[] {
  if (agency.types && agency.types.length > 0) return agency.types;
  return agency.type ? [agency.type] : [];
}

export function agencyTypeLabel(type: string | null): string {
  if (type === null) return UNCLASSIFIED_LABEL;
  return AGENCY_TYPE_LABELS[type] ?? type;
}

export function continentLabel(continent: string | null): string {
  if (continent === null) return "Other";
  return CONTINENT_LABELS[continent] ?? continent;
}
